[package]
name = "krumpli_tubers"
version = "0.1.0"
description = "API wrappers for Invidious and PeerTube."
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jiff.workspace = true
mime.workspace = true
serde.workspace = true
serde_bytes.workspace = true
smallvec.workspace = true
smol_str.workspace = true
url.workspace = true

[dev-dependencies]
krumplipure = { path = "../krumplipure" }

serde_json.workspace = true
