# Based off of: https://codekobold.io/gitlab-ci-for-rust.html

image: "rust:latest"

include:
  - component: gitlab.com/components/sast/sast@main

default:
  interruptible: true
  cache:
    key:
      files: [ "Cargo.lock" ]
    paths: [.cargo, target]
  artifacts:
    when: always
    paths: [.cargo, target]

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  RUSTFLAGS: "-Dwarnings"
  RUSTUP_HOME: "${CI_PROJECT_DIR}/.rustup"
  RUSTUP_TOOLCHAIN: "stable"
  SECRET_DETECTION_ENABLED: "true"

format_check:
  script:
    - rustup component add rustfmt
    - cargo fmt --check

lint:
  script:
    - rustup component add clippy
    - cargo clippy --workspace --all-features --all-targets --bins --tests

test:
  script:
    - cargo test --workspace --all-features --verbose -- --nocapture
