[package]
name = "krumplipure"
version = "0.1.0"
description = "Client implementation for KrumpliTube."
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
krumpli_tubers = { path = "../krumpli_tubers" }

http.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[dev-dependencies]
test-log.workspace = true
